sudo: false

matrix:
  include:
    - language: elixir
      elixir: '1.9.1'
      otp_release: '22.0'
      script:
        - mix format --check-formatted
        - mix credo --strict
        - mix test

    - language: elixir
      elixir: '1.6'
      otp_release: '20.3'
      script: 'mix test'

deploy:
  skip_cleanup: true
  provider: script
  script: bash deploy/deploy.sh
  on:
    tags: true
    branch: master
    elixir: '1.9.1'
