name: Tests

on:
  push:
    branches:
      - '*'
      - 'feat/*'
      - 'docs/*'
      - 'fix/*'
      - 'refactor/*'
    tags:
      - '!*'
      - '!*/**'
      - '!**/**'

jobs:
  test-elixir-latest:
    name: Elixir 1.10 - Full

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1

    - uses: actions/setup-elixir@v1
      with:
        otp-version: 22.x
        elixir-version: 1.10.x

    - name: Install dependencies
      run: |
        mix local.rebar --force
        mix local.hex --force
        mix deps.get

    - name: Check formatting
      run: mix format --check-formatted

    - name: Run credo
      run: mix credo --strict
  
    - name: Test code
      run: mix test --cover
