name: Tests

on:
  push:
    branches:
      - '*'
      - 'feat/*'
      - 'docs/*'
      - 'fix/*'
      - 'refactor/*'
    tags:
      - '!*'
      - '!*/**'
      - '!**/**'

jobs:
  test-elixir-min-version:
    name: Elixir 1.6 - Only Tests

    runs-on: ubuntu-latest

    container:
      image: spaceeec/elixir:1.6-slim
    
    steps:
    - uses: actions/checkout@v1
    - name: Install dependencies
      run: |
        mix local.rebar --force
        mix local.hex --force
        mix deps.get

    - name: Run tests
      run: mix test

  test-elixir-latest:
    name: Elixir 1.9 - Full

    runs-on: ubuntu-latest

    container:
      image: spaceeec/elixir:1.9-slim

    steps:
    - uses: actions/checkout@v1
    - name: Install dependencies
      run: |
        mix local.rebar --force
        mix local.hex --force
        mix deps.get

    - name: Check formatting
      run: mix format --check-formatted

    - name: Run credo
      run: mix credo --strict
  
    - name: Test code
      run: mix test